/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "my_string.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "my_string.h"

START_TEST(memchr1) {
  char str1[] = "Find the pointer to t";
  ck_assert_ptr_eq(memchr(str1, 't', 10), my_memchr(str1, 't', 10));
  ck_assert_ptr_eq(memchr(str1, 'x', 10), my_memchr(str1, 'x', 10));
  ck_assert_ptr_eq(memchr(str1, 't', 5), my_memchr(str1, 't', 5));
}
END_TEST

START_TEST(memcmp2) {
  char str1[] = "DWgaOtP12df0";
  char str2[] = "DWGAOTP12DF0";
  ck_assert_int_eq(memcmp(str1, str2, 1), my_memcmp(str1, str2, 1));
  ck_assert_int_gt(memcmp(str1, str2, 3), 0);
  ck_assert_int_gt(my_memcmp(str1, str2, 3), 0);
  ck_assert_int_lt(memcmp(str2, str1, 3), 0);
  ck_assert_int_lt(my_memcmp(str2, str1, 3), 0);
}
END_TEST

START_TEST(memcpy3) {
  char dest[] = "copy this string";
  char src[] = "copy that string";
  ck_assert_ptr_eq(memcpy(dest, src, 10), my_memcpy(dest, src, 10));
  ck_assert_str_eq(memcpy(dest, src, 10), my_memcpy(dest, src, 10));
}
END_TEST

START_TEST(memmove4) {
  char str1[256] = "I am going";
  char *str2 = "not going";
  char *str3 = "";
  ck_assert_ptr_eq(memmove(str1 + 5, str2, 9), my_memmove(str1 + 5, str2, 9));
  ck_assert_str_eq(memmove(str1 + 5, str2, 9), my_memmove(str1 + 5, str2, 9));
  ck_assert_str_eq(memmove(str1 + 5, str3, 1), my_memmove(str1 + 5, str3, 1));
}
END_TEST

START_TEST(memset5) {
  char ptr[] = "memset is usefull";
  ck_assert_ptr_eq(memset(ptr, '?', 6), my_memset(ptr, '?', 6));
  ck_assert_str_eq(memset(ptr, '?', 6), my_memset(ptr, '?', 6));
}
END_TEST

START_TEST(strcat6) {
  char dest[256] = "Concatenated ";
  char source[] = "strings!";
  ck_assert_ptr_eq(strcat(dest, source), my_strcat(dest, source));
  ck_assert_str_eq(strcat(dest, source), my_strcat(dest, source));
}
END_TEST

START_TEST(strncat7) {
  char dest[256] = "Concatenated ";
  char source[] = "strings!";
  ck_assert_ptr_eq(strncat(dest, source, 6), my_strncat(dest, source, 6));
  ck_assert_str_eq(strncat(dest, source, 6), my_strncat(dest, source, 6));
}
END_TEST

START_TEST(strchr8) {
  char str1[] = "Find the pointer to t";
  ck_assert_ptr_eq(strchr(str1, 't'), my_strchr(str1, 't'));
  ck_assert_ptr_eq(strchr(str1, 'x'), my_strchr(str1, 'x'));
}
END_TEST

START_TEST(strcmp9) {
  const char str1[] = "ABC";
  const char str2[] = "ABC";
  const char str3[] = "abc";
  ck_assert_int_eq(strcmp(str1, str2), my_strcmp(str1, str2));
  ck_assert_int_gt(strcmp(str3, str1), 0);
  ck_assert_int_gt(my_strcmp(str3, str1), 0);
  ck_assert_int_lt(strcmp(str1, str3), 0);
  ck_assert_int_lt(my_strcmp(str1, str3), 0);
}
END_TEST

START_TEST(strncmp10) {
  const char str1[] = "ABCD";
  const char str2[] = "ABcd";
  ck_assert_int_eq(strncmp(str1, str2, 2), my_strncmp(str1, str2, 2));
  ck_assert_int_gt(strncmp(str2, str1, 3), 0);
  ck_assert_int_gt(my_strncmp(str2, str1, 3), 0);
  ck_assert_int_lt(strncmp(str1, str2, 3), 0);
  ck_assert_int_lt(my_strncmp(str1, str2, 3), 0);
}
END_TEST

START_TEST(strcpy11) {
  char dest[256];
  const char *src = "Copy this string.";
  ck_assert_ptr_eq(strcpy(dest, src), my_strcpy(dest, src));
  ck_assert_ptr_eq(strcpy(dest, src), my_strcpy(dest, src));
  ck_assert_ptr_eq(strcpy(dest, "COPY"), my_strcpy(dest, "COPY"));
  ck_assert_ptr_eq(strcpy(dest, "COPY"), my_strcpy(dest, "COPY"));
}
END_TEST

START_TEST(strncpy12) {
  char dest[256];
  const char *src = "Copy this string.";
  ck_assert_ptr_eq(strncpy(dest, src, 9), my_strncpy(dest, src, 9));
  ck_assert_ptr_eq(strncpy(dest, src, 9), my_strncpy(dest, src, 9));
  ck_assert_ptr_eq(strncpy(dest, "COPY", 3), my_strncpy(dest, "COPY", 3));
  ck_assert_ptr_eq(strncpy(dest, "COPY", 3), my_strncpy(dest, "COPY", 3));
}
END_TEST

START_TEST(strcspn13) {
  char str1[] = "fcba73";
  char str2[] = "1234567890";
  char str3[] = "+=!";
  ck_assert_int_eq(strcspn(str1, str2), my_strcspn(str1, str2));
  ck_assert_int_eq(strcspn(str1, str3), my_strcspn(str1, str3));
}
END_TEST

START_TEST(strerror14) {
  ck_assert_str_eq(my_strerror(0), strerror(0));
  ck_assert_str_eq(my_strerror(1), strerror(1));
  ck_assert_str_eq(my_strerror(33), strerror(33));
  ck_assert_str_eq(my_strerror(150), strerror(150));
  ck_assert_str_eq(my_strerror(-28), strerror(-28));
  ck_assert_str_eq(my_strerror(107), strerror(107));
}
END_TEST

START_TEST(strlen15) {
  char str1[20] = "It is a string!";
  ck_assert_int_eq(strlen(str1), my_strlen(str1));
  char str2[] = "";
  ck_assert_int_eq(strlen(str2), my_strlen(str2));
}
END_TEST

START_TEST(strpbrk16) {
  const char str1[] = "Find some characters here";
  const char str2[] = "oh";
  const char str3[] = "xyz";
  ck_assert_ptr_eq(strpbrk(str1, str2), my_strpbrk(str1, str2));
  ck_assert_ptr_eq(strpbrk(str1, str3), my_strpbrk(str1, str3));
}
END_TEST

START_TEST(strrchar17) {
  char str1[] = "Find the pointer to t";
  ck_assert_ptr_eq(strrchr(str1, 't'), my_strrchr(str1, 't'));
  ck_assert_ptr_eq(strrchr(str1, 'x'), my_strrchr(str1, 'x'));
}
END_TEST

START_TEST(strspn18) {
  const char str1[] = "42nd";
  const char str2[] = "1234567890";
  const char str3[] = "the42nd";
  ck_assert_int_eq(strspn(str1, str2), my_strspn(str1, str2));
  ck_assert_int_eq(strspn(str3, str2), my_strspn(str3, str2));
}
END_TEST

START_TEST(strstr19) {
  const char str1[] = "Can you find anything here?";
  const char str2[] = "thing";
  const char str3[] = "needle?";
  ck_assert_ptr_eq(strstr(str1, str2), my_strstr(str1, str2));
  ck_assert_ptr_eq(strstr(str1, str3), my_strstr(str1, str3));
}
END_TEST

START_TEST(strtok20) {
  char string[] = "Here@@@,,,are----some*****delimiters";
  const char delim[] = "-*@,";
  ck_assert_ptr_eq(strtok(string, delim), my_strtok(string, delim));
  ck_assert_str_eq(strtok(string, delim), my_strtok(string, delim));
  ck_assert_ptr_eq(strtok(NULL, delim), my_strtok(NULL, delim));
  ck_assert_ptr_eq(strtok(NULL, delim), my_strtok(NULL, delim));
}
END_TEST

START_TEST(five) {
  char strr[] = "aBscffdF";
  char *new = my_to_upper(strr);
  ck_assert_str_eq(new, "ABSCFFDF");
  new = my_to_lower(strr);
  ck_assert_str_eq(new, "abscffdf");
  char str1[] = "123 ", str2[] = "456";
  new = my_insert(str1, str2, 3);
  ck_assert_str_eq(new, "123456 ");
  new = my_trim(new, "12 ");
  ck_assert_str_eq(new, "3456");
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, memchr1);
  tcase_add_test(tc1_1, memcmp2);
  tcase_add_test(tc1_1, memcpy3);
  tcase_add_test(tc1_1, memmove4);
  tcase_add_test(tc1_1, memset5);
  tcase_add_test(tc1_1, strcat6);
  tcase_add_test(tc1_1, strncat7);
  tcase_add_test(tc1_1, strchr8);
  tcase_add_test(tc1_1, strcmp9);
  tcase_add_test(tc1_1, strncmp10);
  tcase_add_test(tc1_1, strcpy11);
  tcase_add_test(tc1_1, strncpy12);
  tcase_add_test(tc1_1, strcspn13);
  tcase_add_test(tc1_1, strerror14);
  tcase_add_test(tc1_1, strlen15);
  tcase_add_test(tc1_1, strpbrk16);
  tcase_add_test(tc1_1, strrchar17);
  tcase_add_test(tc1_1, strspn18);
  tcase_add_test(tc1_1, strstr19);
  tcase_add_test(tc1_1, strtok20);
  tcase_add_test(tc1_1, five);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
